# Generated by Django 4.1.2 on 2022-12-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appundercoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=40)),
                ('contraseña_user', models.CharField(max_length=40)),
            ],
        ),
    ]
