# Generated by Django 4.1.2 on 2022-12-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appundercoder', '0002_nuevouser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasegym',
            old_name='clase',
            new_name='class_name',
        ),
    ]
