# Generated by Django 4.1.2 on 2022-12-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appundercoder', '0003_rename_clase_clasegym_class_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NuevoUser',
        ),
    ]
